version: "3.8"

services:
  app:
    image: ghcr.io/fluowai/imobili-ria-smart:latest
    environment:
      VITE_SUPABASE_URL: "https://cgxujqgzucwgdlcssrka.supabase.co"
      VITE_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNneHVqcWd6dWN3Z2RsY3NzcmthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQyOTE1MjUsImV4cCI6MjA5OTg2NzUyNX0.jzVI-tlrZHvaIncHNB7z9ah4-i89L8roTdQIMlKu-Xc"
      VITE_SUPABASE_PUBLISHABLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNneHVqcWd6dWN3Z2RsY3NzcmthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQyOTE1MjUsImV4cCI6MjA5OTg2NzUyNX0.jzVI-tlrZHvaIncHNB7z9ah4-i89L8roTdQIMlKu-Xc"
      JWT_SECRET: "uiRbeadX1F/vtLbJe9k7R3FNkYYZld5eLe1kdwmjIhPDYPe+1I2RzPuoLqonsMBFR8gO2Zn/ScTub7jGYdPwPw=="
    networks:
      - woopanel1
      - imobfluow_internal
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        order: stop-first
        failure_action: rollback
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=woopanel1"
        - "traefik.http.routers.imobfluow_app.rule=Host(`imobfluow.wootech.com.br`)"
        - "traefik.http.routers.imobfluow_app.entrypoints=websecure"
        - "traefik.http.routers.imobfluow_app.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.imobfluow_app.priority=1"
        - "traefik.http.routers.imobfluow_app.service=imobfluow_app"
        - "traefik.http.services.imobfluow_app.loadbalancer.server.port=3000"

  whatsapp-service:
    image: ghcr.io/fluowai/whatsmeow:latest
    environment:
      DATABASE_URL: "postgres://postgres.dizpobswwvwddqixyivk:Fluow%4065261@aws-0-sa-east-1.pooler.supabase.com:6543/postgres"
      SUPABASE_JWT_SECRET: "uiRbeadX1F/vtLbJe9k7R3FNkYYZld5eLe1kdwmjIhPDYPe+1I2RzPuoLqonsMBFR8gO2Zn/ScTub7jGYdPwPw=="
    networks:
      - woopanel1
      - imobfluow_internal
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        order: stop-first
        failure_action: rollback
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=woopanel1"
        - "traefik.http.routers.imobfluow_wa.rule=Host(`imobfluow.wootech.com.br`) && PathPrefix(`/wa`)"
        - "traefik.http.routers.imobfluow_wa.entrypoints=websecure"
        - "traefik.http.routers.imobfluow_wa.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.imobfluow_wa.priority=10"
        - "traefik.http.routers.imobfluow_wa.service=imobfluow_wa"
        - "traefik.http.services.imobfluow_wa.loadbalancer.server.port=8080"

networks:
  woopanel1:
    external: true
    name: woopanel1

  imobfluow_internal:
    driver: overlay
    attachable: true
