version: "3.8"

services:
  app:
    # URL completa do GHCR para o Portainer conseguir baixar
    image: ghcr.io/fluowai/imobili-ria-smart:latest
    environment:
      # Insira aqui as variáveis do Supabase e outras que sua aplicação usa
      VITE_SUPABASE_URL: "${VITE_SUPABASE_URL}"
      VITE_SUPABASE_ANON_KEY: "${VITE_SUPABASE_ANON_KEY}"
      JWT_SECRET: "${JWT_SECRET}"
    networks:
      - woopanel1
      - imobfluow_internal
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        order: stop-first
        failure_action: rollback
      rollback_config:
        order: stop-first
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=woopanel1"
        - "traefik.http.routers.imobfluow_app.rule=Host(`imobfluow.wootech.com.br`)"
        - "traefik.http.routers.imobfluow_app.entrypoints=websecure"
        - "traefik.http.routers.imobfluow_app.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.imobfluow_app.priority=10"
        - "traefik.http.routers.imobfluow_app.service=imobfluow_app"
        - "traefik.http.services.imobfluow_app.loadbalancer.server.port=3000"

networks:
  woopanel1:
    external: true
    name: woopanel1

  imobfluow_internal:
    driver: overlay
    attachable: true
