/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppSuporteRouteImport } from './routes/app.suporte'
import { Route as AppSiteRouteImport } from './routes/app.site'
import { Route as AppSimuladorRouteImport } from './routes/app.simulador'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppQuizRouteImport } from './routes/app.quiz'
import { Route as AppMetasRouteImport } from './routes/app.metas'
import { Route as AppMensagensRouteImport } from './routes/app.mensagens'
import { Route as AppMatchmakingRouteImport } from './routes/app.matchmaking'
import { Route as AppLandingPagesRouteImport } from './routes/app.landing-pages'
import { Route as AppKanbanRouteImport } from './routes/app.kanban'
import { Route as AppIntegracoesRouteImport } from './routes/app.integracoes'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppEmailRouteImport } from './routes/app.email'
import { Route as AppEditorRouteImport } from './routes/app.editor'
import { Route as AppDocumentosRouteImport } from './routes/app.documentos'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCrmRouteImport } from './routes/app.crm'
import { Route as AppContratosRouteImport } from './routes/app.contratos'
import { Route as AppConfigurarSiteRouteImport } from './routes/app.configurar-site'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppConexoesRouteImport } from './routes/app.conexoes'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppAgentesIaRouteImport } from './routes/app.agentes-ia'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminSuporteRouteImport } from './routes/admin.suporte'
import { Route as AdminStorageRouteImport } from './routes/admin.storage'
import { Route as AdminPlanosRouteImport } from './routes/admin.planos'
import { Route as AdminMonitoringRouteImport } from './routes/admin.monitoring'
import { Route as AdminMigracaoRouteImport } from './routes/admin.migracao'
import { Route as AdminMarketingRouteImport } from './routes/admin.marketing'
import { Route as AdminImportadorIaRouteImport } from './routes/admin.importador-ia'
import { Route as AdminImobiliariasRouteImport } from './routes/admin.imobiliarias'
import { Route as AdminFeatureFlagsRouteImport } from './routes/admin.feature-flags'
import { Route as AdminEquipeRouteImport } from './routes/admin.equipe'
import { Route as AdminDominiosRouteImport } from './routes/admin.dominios'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminConsultoriaRouteImport } from './routes/admin.consultoria'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminAuditLogRouteImport } from './routes/admin.audit-log'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AppUrbanoLoteamentosRouteImport } from './routes/app.urbano.loteamentos'
import { Route as AppUrbanoLocacaoRouteImport } from './routes/app.urbano.locacao'
import { Route as AppUrbanoImoveisRouteImport } from './routes/app.urbano.imoveis'
import { Route as AppUrbanoCondominiosRouteImport } from './routes/app.urbano.condominios'
import { Route as AppUrbanoChavesRouteImport } from './routes/app.urbano.chaves'
import { Route as AppRuralValuationRouteImport } from './routes/app.rural.valuation'
import { Route as AppRuralTerritorioRouteImport } from './routes/app.rural.territorio'
import { Route as AppRuralImoveisRouteImport } from './routes/app.rural.imoveis'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSuporteRoute = AppSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AppRoute,
} as any)
const AppSiteRoute = AppSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AppRoute,
} as any)
const AppSimuladorRoute = AppSimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizRoute = AppQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AppRoute,
} as any)
const AppMetasRoute = AppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppMensagensRoute = AppMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchmakingRoute = AppMatchmakingRouteImport.update({
  id: '/matchmaking',
  path: '/matchmaking',
  getParentRoute: () => AppRoute,
} as any)
const AppLandingPagesRoute = AppLandingPagesRouteImport.update({
  id: '/landing-pages',
  path: '/landing-pages',
  getParentRoute: () => AppRoute,
} as any)
const AppKanbanRoute = AppKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegracoesRoute = AppIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailRoute = AppEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AppRoute,
} as any)
const AppEditorRoute = AppEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosRoute = AppDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosRoute = AppContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigurarSiteRoute = AppConfigurarSiteRouteImport.update({
  id: '/configurar-site',
  path: '/configurar-site',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppConexoesRoute = AppConexoesRouteImport.update({
  id: '/conexoes',
  path: '/conexoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentesIaRoute = AppAgentesIaRouteImport.update({
  id: '/agentes-ia',
  path: '/agentes-ia',
  getParentRoute: () => AppRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuporteRoute = AdminSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStorageRoute = AdminStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMonitoringRoute = AdminMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMigracaoRoute = AdminMigracaoRouteImport.update({
  id: '/migracao',
  path: '/migracao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportadorIaRoute = AdminImportadorIaRouteImport.update({
  id: '/importador-ia',
  path: '/importador-ia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImobiliariasRoute = AdminImobiliariasRouteImport.update({
  id: '/imobiliarias',
  path: '/imobiliarias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeatureFlagsRoute = AdminFeatureFlagsRouteImport.update({
  id: '/feature-flags',
  path: '/feature-flags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipeRoute = AdminEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDominiosRoute = AdminDominiosRouteImport.update({
  id: '/dominios',
  path: '/dominios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConsultoriaRoute = AdminConsultoriaRouteImport.update({
  id: '/consultoria',
  path: '/consultoria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AppUrbanoLoteamentosRoute = AppUrbanoLoteamentosRouteImport.update({
  id: '/urbano/loteamentos',
  path: '/urbano/loteamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppUrbanoLocacaoRoute = AppUrbanoLocacaoRouteImport.update({
  id: '/urbano/locacao',
  path: '/urbano/locacao',
  getParentRoute: () => AppRoute,
} as any)
const AppUrbanoImoveisRoute = AppUrbanoImoveisRouteImport.update({
  id: '/urbano/imoveis',
  path: '/urbano/imoveis',
  getParentRoute: () => AppRoute,
} as any)
const AppUrbanoCondominiosRoute = AppUrbanoCondominiosRouteImport.update({
  id: '/urbano/condominios',
  path: '/urbano/condominios',
  getParentRoute: () => AppRoute,
} as any)
const AppUrbanoChavesRoute = AppUrbanoChavesRouteImport.update({
  id: '/urbano/chaves',
  path: '/urbano/chaves',
  getParentRoute: () => AppRoute,
} as any)
const AppRuralValuationRoute = AppRuralValuationRouteImport.update({
  id: '/rural/valuation',
  path: '/rural/valuation',
  getParentRoute: () => AppRoute,
} as any)
const AppRuralTerritorioRoute = AppRuralTerritorioRouteImport.update({
  id: '/rural/territorio',
  path: '/rural/territorio',
  getParentRoute: () => AppRoute,
} as any)
const AppRuralImoveisRoute = AppRuralImoveisRouteImport.update({
  id: '/rural/imoveis',
  path: '/rural/imoveis',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/consultoria': typeof AdminConsultoriaRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dominios': typeof AdminDominiosRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/imobiliarias': typeof AdminImobiliariasRoute
  '/admin/importador-ia': typeof AdminImportadorIaRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/migracao': typeof AdminMigracaoRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/app/agentes-ia': typeof AppAgentesIaRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/conexoes': typeof AppConexoesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/configurar-site': typeof AppConfigurarSiteRoute
  '/app/contratos': typeof AppContratosRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/editor': typeof AppEditorRoute
  '/app/email': typeof AppEmailRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/integracoes': typeof AppIntegracoesRoute
  '/app/kanban': typeof AppKanbanRoute
  '/app/landing-pages': typeof AppLandingPagesRoute
  '/app/matchmaking': typeof AppMatchmakingRoute
  '/app/mensagens': typeof AppMensagensRoute
  '/app/metas': typeof AppMetasRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/simulador': typeof AppSimuladorRoute
  '/app/site': typeof AppSiteRoute
  '/app/suporte': typeof AppSuporteRoute
  '/auth/login': typeof AuthLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/rural/imoveis': typeof AppRuralImoveisRoute
  '/app/rural/territorio': typeof AppRuralTerritorioRoute
  '/app/rural/valuation': typeof AppRuralValuationRoute
  '/app/urbano/chaves': typeof AppUrbanoChavesRoute
  '/app/urbano/condominios': typeof AppUrbanoCondominiosRoute
  '/app/urbano/imoveis': typeof AppUrbanoImoveisRoute
  '/app/urbano/locacao': typeof AppUrbanoLocacaoRoute
  '/app/urbano/loteamentos': typeof AppUrbanoLoteamentosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/consultoria': typeof AdminConsultoriaRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dominios': typeof AdminDominiosRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/imobiliarias': typeof AdminImobiliariasRoute
  '/admin/importador-ia': typeof AdminImportadorIaRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/migracao': typeof AdminMigracaoRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/app/agentes-ia': typeof AppAgentesIaRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/conexoes': typeof AppConexoesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/configurar-site': typeof AppConfigurarSiteRoute
  '/app/contratos': typeof AppContratosRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/editor': typeof AppEditorRoute
  '/app/email': typeof AppEmailRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/integracoes': typeof AppIntegracoesRoute
  '/app/kanban': typeof AppKanbanRoute
  '/app/landing-pages': typeof AppLandingPagesRoute
  '/app/matchmaking': typeof AppMatchmakingRoute
  '/app/mensagens': typeof AppMensagensRoute
  '/app/metas': typeof AppMetasRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/simulador': typeof AppSimuladorRoute
  '/app/site': typeof AppSiteRoute
  '/app/suporte': typeof AppSuporteRoute
  '/auth/login': typeof AuthLoginRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/app/rural/imoveis': typeof AppRuralImoveisRoute
  '/app/rural/territorio': typeof AppRuralTerritorioRoute
  '/app/rural/valuation': typeof AppRuralValuationRoute
  '/app/urbano/chaves': typeof AppUrbanoChavesRoute
  '/app/urbano/condominios': typeof AppUrbanoCondominiosRoute
  '/app/urbano/imoveis': typeof AppUrbanoImoveisRoute
  '/app/urbano/locacao': typeof AppUrbanoLocacaoRoute
  '/app/urbano/loteamentos': typeof AppUrbanoLoteamentosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/consultoria': typeof AdminConsultoriaRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dominios': typeof AdminDominiosRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/imobiliarias': typeof AdminImobiliariasRoute
  '/admin/importador-ia': typeof AdminImportadorIaRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/migracao': typeof AdminMigracaoRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/app/agentes-ia': typeof AppAgentesIaRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/conexoes': typeof AppConexoesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/configurar-site': typeof AppConfigurarSiteRoute
  '/app/contratos': typeof AppContratosRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/editor': typeof AppEditorRoute
  '/app/email': typeof AppEmailRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/integracoes': typeof AppIntegracoesRoute
  '/app/kanban': typeof AppKanbanRoute
  '/app/landing-pages': typeof AppLandingPagesRoute
  '/app/matchmaking': typeof AppMatchmakingRoute
  '/app/mensagens': typeof AppMensagensRoute
  '/app/metas': typeof AppMetasRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/simulador': typeof AppSimuladorRoute
  '/app/site': typeof AppSiteRoute
  '/app/suporte': typeof AppSuporteRoute
  '/auth/login': typeof AuthLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/rural/imoveis': typeof AppRuralImoveisRoute
  '/app/rural/territorio': typeof AppRuralTerritorioRoute
  '/app/rural/valuation': typeof AppRuralValuationRoute
  '/app/urbano/chaves': typeof AppUrbanoChavesRoute
  '/app/urbano/condominios': typeof AppUrbanoCondominiosRoute
  '/app/urbano/imoveis': typeof AppUrbanoImoveisRoute
  '/app/urbano/locacao': typeof AppUrbanoLocacaoRoute
  '/app/urbano/loteamentos': typeof AppUrbanoLoteamentosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/onboarding'
    | '/admin/analytics'
    | '/admin/audit-log'
    | '/admin/billing'
    | '/admin/configuracoes'
    | '/admin/consultoria'
    | '/admin/dashboard'
    | '/admin/dominios'
    | '/admin/equipe'
    | '/admin/feature-flags'
    | '/admin/imobiliarias'
    | '/admin/importador-ia'
    | '/admin/marketing'
    | '/admin/migracao'
    | '/admin/monitoring'
    | '/admin/planos'
    | '/admin/storage'
    | '/admin/suporte'
    | '/admin/templates'
    | '/app/agentes-ia'
    | '/app/clientes'
    | '/app/conexoes'
    | '/app/configuracoes'
    | '/app/configurar-site'
    | '/app/contratos'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/documentos'
    | '/app/editor'
    | '/app/email'
    | '/app/financeiro'
    | '/app/integracoes'
    | '/app/kanban'
    | '/app/landing-pages'
    | '/app/matchmaking'
    | '/app/mensagens'
    | '/app/metas'
    | '/app/quiz'
    | '/app/relatorios'
    | '/app/simulador'
    | '/app/site'
    | '/app/suporte'
    | '/auth/login'
    | '/admin/'
    | '/app/'
    | '/app/rural/imoveis'
    | '/app/rural/territorio'
    | '/app/rural/valuation'
    | '/app/urbano/chaves'
    | '/app/urbano/condominios'
    | '/app/urbano/imoveis'
    | '/app/urbano/locacao'
    | '/app/urbano/loteamentos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/admin/analytics'
    | '/admin/audit-log'
    | '/admin/billing'
    | '/admin/configuracoes'
    | '/admin/consultoria'
    | '/admin/dashboard'
    | '/admin/dominios'
    | '/admin/equipe'
    | '/admin/feature-flags'
    | '/admin/imobiliarias'
    | '/admin/importador-ia'
    | '/admin/marketing'
    | '/admin/migracao'
    | '/admin/monitoring'
    | '/admin/planos'
    | '/admin/storage'
    | '/admin/suporte'
    | '/admin/templates'
    | '/app/agentes-ia'
    | '/app/clientes'
    | '/app/conexoes'
    | '/app/configuracoes'
    | '/app/configurar-site'
    | '/app/contratos'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/documentos'
    | '/app/editor'
    | '/app/email'
    | '/app/financeiro'
    | '/app/integracoes'
    | '/app/kanban'
    | '/app/landing-pages'
    | '/app/matchmaking'
    | '/app/mensagens'
    | '/app/metas'
    | '/app/quiz'
    | '/app/relatorios'
    | '/app/simulador'
    | '/app/site'
    | '/app/suporte'
    | '/auth/login'
    | '/admin'
    | '/app'
    | '/app/rural/imoveis'
    | '/app/rural/territorio'
    | '/app/rural/valuation'
    | '/app/urbano/chaves'
    | '/app/urbano/condominios'
    | '/app/urbano/imoveis'
    | '/app/urbano/locacao'
    | '/app/urbano/loteamentos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/onboarding'
    | '/admin/analytics'
    | '/admin/audit-log'
    | '/admin/billing'
    | '/admin/configuracoes'
    | '/admin/consultoria'
    | '/admin/dashboard'
    | '/admin/dominios'
    | '/admin/equipe'
    | '/admin/feature-flags'
    | '/admin/imobiliarias'
    | '/admin/importador-ia'
    | '/admin/marketing'
    | '/admin/migracao'
    | '/admin/monitoring'
    | '/admin/planos'
    | '/admin/storage'
    | '/admin/suporte'
    | '/admin/templates'
    | '/app/agentes-ia'
    | '/app/clientes'
    | '/app/conexoes'
    | '/app/configuracoes'
    | '/app/configurar-site'
    | '/app/contratos'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/documentos'
    | '/app/editor'
    | '/app/email'
    | '/app/financeiro'
    | '/app/integracoes'
    | '/app/kanban'
    | '/app/landing-pages'
    | '/app/matchmaking'
    | '/app/mensagens'
    | '/app/metas'
    | '/app/quiz'
    | '/app/relatorios'
    | '/app/simulador'
    | '/app/site'
    | '/app/suporte'
    | '/auth/login'
    | '/admin/'
    | '/app/'
    | '/app/rural/imoveis'
    | '/app/rural/territorio'
    | '/app/rural/valuation'
    | '/app/urbano/chaves'
    | '/app/urbano/condominios'
    | '/app/urbano/imoveis'
    | '/app/urbano/locacao'
    | '/app/urbano/loteamentos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/suporte': {
      id: '/app/suporte'
      path: '/suporte'
      fullPath: '/app/suporte'
      preLoaderRoute: typeof AppSuporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/site': {
      id: '/app/site'
      path: '/site'
      fullPath: '/app/site'
      preLoaderRoute: typeof AppSiteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/simulador': {
      id: '/app/simulador'
      path: '/simulador'
      fullPath: '/app/simulador'
      preLoaderRoute: typeof AppSimuladorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quiz': {
      id: '/app/quiz'
      path: '/quiz'
      fullPath: '/app/quiz'
      preLoaderRoute: typeof AppQuizRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/metas': {
      id: '/app/metas'
      path: '/metas'
      fullPath: '/app/metas'
      preLoaderRoute: typeof AppMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mensagens': {
      id: '/app/mensagens'
      path: '/mensagens'
      fullPath: '/app/mensagens'
      preLoaderRoute: typeof AppMensagensRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/matchmaking': {
      id: '/app/matchmaking'
      path: '/matchmaking'
      fullPath: '/app/matchmaking'
      preLoaderRoute: typeof AppMatchmakingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/landing-pages': {
      id: '/app/landing-pages'
      path: '/landing-pages'
      fullPath: '/app/landing-pages'
      preLoaderRoute: typeof AppLandingPagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kanban': {
      id: '/app/kanban'
      path: '/kanban'
      fullPath: '/app/kanban'
      preLoaderRoute: typeof AppKanbanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integracoes': {
      id: '/app/integracoes'
      path: '/integracoes'
      fullPath: '/app/integracoes'
      preLoaderRoute: typeof AppIntegracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/email': {
      id: '/app/email'
      path: '/email'
      fullPath: '/app/email'
      preLoaderRoute: typeof AppEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/editor': {
      id: '/app/editor'
      path: '/editor'
      fullPath: '/app/editor'
      preLoaderRoute: typeof AppEditorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documentos': {
      id: '/app/documentos'
      path: '/documentos'
      fullPath: '/app/documentos'
      preLoaderRoute: typeof AppDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contratos': {
      id: '/app/contratos'
      path: '/contratos'
      fullPath: '/app/contratos'
      preLoaderRoute: typeof AppContratosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configurar-site': {
      id: '/app/configurar-site'
      path: '/configurar-site'
      fullPath: '/app/configurar-site'
      preLoaderRoute: typeof AppConfigurarSiteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conexoes': {
      id: '/app/conexoes'
      path: '/conexoes'
      fullPath: '/app/conexoes'
      preLoaderRoute: typeof AppConexoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agentes-ia': {
      id: '/app/agentes-ia'
      path: '/agentes-ia'
      fullPath: '/app/agentes-ia'
      preLoaderRoute: typeof AppAgentesIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suporte': {
      id: '/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AdminSuporteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/storage': {
      id: '/admin/storage'
      path: '/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof AdminStorageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/monitoring': {
      id: '/admin/monitoring'
      path: '/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminMonitoringRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/migracao': {
      id: '/admin/migracao'
      path: '/migracao'
      fullPath: '/admin/migracao'
      preLoaderRoute: typeof AdminMigracaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/importador-ia': {
      id: '/admin/importador-ia'
      path: '/importador-ia'
      fullPath: '/admin/importador-ia'
      preLoaderRoute: typeof AdminImportadorIaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/imobiliarias': {
      id: '/admin/imobiliarias'
      path: '/imobiliarias'
      fullPath: '/admin/imobiliarias'
      preLoaderRoute: typeof AdminImobiliariasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feature-flags': {
      id: '/admin/feature-flags'
      path: '/feature-flags'
      fullPath: '/admin/feature-flags'
      preLoaderRoute: typeof AdminFeatureFlagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipe': {
      id: '/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AdminEquipeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dominios': {
      id: '/admin/dominios'
      path: '/dominios'
      fullPath: '/admin/dominios'
      preLoaderRoute: typeof AdminDominiosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/consultoria': {
      id: '/admin/consultoria'
      path: '/consultoria'
      fullPath: '/admin/consultoria'
      preLoaderRoute: typeof AdminConsultoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/urbano/loteamentos': {
      id: '/app/urbano/loteamentos'
      path: '/urbano/loteamentos'
      fullPath: '/app/urbano/loteamentos'
      preLoaderRoute: typeof AppUrbanoLoteamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/urbano/locacao': {
      id: '/app/urbano/locacao'
      path: '/urbano/locacao'
      fullPath: '/app/urbano/locacao'
      preLoaderRoute: typeof AppUrbanoLocacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/urbano/imoveis': {
      id: '/app/urbano/imoveis'
      path: '/urbano/imoveis'
      fullPath: '/app/urbano/imoveis'
      preLoaderRoute: typeof AppUrbanoImoveisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/urbano/condominios': {
      id: '/app/urbano/condominios'
      path: '/urbano/condominios'
      fullPath: '/app/urbano/condominios'
      preLoaderRoute: typeof AppUrbanoCondominiosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/urbano/chaves': {
      id: '/app/urbano/chaves'
      path: '/urbano/chaves'
      fullPath: '/app/urbano/chaves'
      preLoaderRoute: typeof AppUrbanoChavesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rural/valuation': {
      id: '/app/rural/valuation'
      path: '/rural/valuation'
      fullPath: '/app/rural/valuation'
      preLoaderRoute: typeof AppRuralValuationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rural/territorio': {
      id: '/app/rural/territorio'
      path: '/rural/territorio'
      fullPath: '/app/rural/territorio'
      preLoaderRoute: typeof AppRuralTerritorioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rural/imoveis': {
      id: '/app/rural/imoveis'
      path: '/rural/imoveis'
      fullPath: '/app/rural/imoveis'
      preLoaderRoute: typeof AppRuralImoveisRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminConsultoriaRoute: typeof AdminConsultoriaRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDominiosRoute: typeof AdminDominiosRoute
  AdminEquipeRoute: typeof AdminEquipeRoute
  AdminFeatureFlagsRoute: typeof AdminFeatureFlagsRoute
  AdminImobiliariasRoute: typeof AdminImobiliariasRoute
  AdminImportadorIaRoute: typeof AdminImportadorIaRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminMigracaoRoute: typeof AdminMigracaoRoute
  AdminMonitoringRoute: typeof AdminMonitoringRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  AdminStorageRoute: typeof AdminStorageRoute
  AdminSuporteRoute: typeof AdminSuporteRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminConsultoriaRoute: AdminConsultoriaRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDominiosRoute: AdminDominiosRoute,
  AdminEquipeRoute: AdminEquipeRoute,
  AdminFeatureFlagsRoute: AdminFeatureFlagsRoute,
  AdminImobiliariasRoute: AdminImobiliariasRoute,
  AdminImportadorIaRoute: AdminImportadorIaRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminMigracaoRoute: AdminMigracaoRoute,
  AdminMonitoringRoute: AdminMonitoringRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  AdminStorageRoute: AdminStorageRoute,
  AdminSuporteRoute: AdminSuporteRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAgentesIaRoute: typeof AppAgentesIaRoute
  AppClientesRoute: typeof AppClientesRoute
  AppConexoesRoute: typeof AppConexoesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppConfigurarSiteRoute: typeof AppConfigurarSiteRoute
  AppContratosRoute: typeof AppContratosRoute
  AppCrmRoute: typeof AppCrmRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentosRoute: typeof AppDocumentosRoute
  AppEditorRoute: typeof AppEditorRoute
  AppEmailRoute: typeof AppEmailRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppIntegracoesRoute: typeof AppIntegracoesRoute
  AppKanbanRoute: typeof AppKanbanRoute
  AppLandingPagesRoute: typeof AppLandingPagesRoute
  AppMatchmakingRoute: typeof AppMatchmakingRoute
  AppMensagensRoute: typeof AppMensagensRoute
  AppMetasRoute: typeof AppMetasRoute
  AppQuizRoute: typeof AppQuizRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppSimuladorRoute: typeof AppSimuladorRoute
  AppSiteRoute: typeof AppSiteRoute
  AppSuporteRoute: typeof AppSuporteRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRuralImoveisRoute: typeof AppRuralImoveisRoute
  AppRuralTerritorioRoute: typeof AppRuralTerritorioRoute
  AppRuralValuationRoute: typeof AppRuralValuationRoute
  AppUrbanoChavesRoute: typeof AppUrbanoChavesRoute
  AppUrbanoCondominiosRoute: typeof AppUrbanoCondominiosRoute
  AppUrbanoImoveisRoute: typeof AppUrbanoImoveisRoute
  AppUrbanoLocacaoRoute: typeof AppUrbanoLocacaoRoute
  AppUrbanoLoteamentosRoute: typeof AppUrbanoLoteamentosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentesIaRoute: AppAgentesIaRoute,
  AppClientesRoute: AppClientesRoute,
  AppConexoesRoute: AppConexoesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppConfigurarSiteRoute: AppConfigurarSiteRoute,
  AppContratosRoute: AppContratosRoute,
  AppCrmRoute: AppCrmRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentosRoute: AppDocumentosRoute,
  AppEditorRoute: AppEditorRoute,
  AppEmailRoute: AppEmailRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppIntegracoesRoute: AppIntegracoesRoute,
  AppKanbanRoute: AppKanbanRoute,
  AppLandingPagesRoute: AppLandingPagesRoute,
  AppMatchmakingRoute: AppMatchmakingRoute,
  AppMensagensRoute: AppMensagensRoute,
  AppMetasRoute: AppMetasRoute,
  AppQuizRoute: AppQuizRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppSimuladorRoute: AppSimuladorRoute,
  AppSiteRoute: AppSiteRoute,
  AppSuporteRoute: AppSuporteRoute,
  AppIndexRoute: AppIndexRoute,
  AppRuralImoveisRoute: AppRuralImoveisRoute,
  AppRuralTerritorioRoute: AppRuralTerritorioRoute,
  AppRuralValuationRoute: AppRuralValuationRoute,
  AppUrbanoChavesRoute: AppUrbanoChavesRoute,
  AppUrbanoCondominiosRoute: AppUrbanoCondominiosRoute,
  AppUrbanoImoveisRoute: AppUrbanoImoveisRoute,
  AppUrbanoLocacaoRoute: AppUrbanoLocacaoRoute,
  AppUrbanoLoteamentosRoute: AppUrbanoLoteamentosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
